import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'

export type Lang = 'en' | 'ar'

const LANGUAGE_KEY = 'app_language'

const dictionary = {
  en: {
    search: 'Search...',
    notifications: 'Notifications',
    noNotifications: 'No notifications',
    light: 'Light',
    dark: 'Dark',
    switchToLight: 'Switch to Light Mode',
    switchToDark: 'Switch to Dark Mode',
    logOut: 'Log Out',
    loggedOut: 'Logged out successfully',
    dashboard: 'Dashboard',
    todaysVisits: "Today's Visits",
    appointments: 'Appointments',
    patients: 'Patients',
    reviews: 'Reviews',
    messages: 'Messages',
    manageStaff: 'Manage Staff',
    schedule: 'Schedule',
    myProfile: 'My Profile',
    users: 'Users',
    statistics: 'Statistics',
    applications: 'Applications',
    supportCenter: 'Support Center',
    systemAdministrator: 'System Administrator',
    secretary: 'Secretary',
    doctor: 'Doctor',
    smartMedical: 'Smart Medical',
    newBooking: 'New booking',
    cancelled: 'Cancelled',
    appointmentUpdate: 'Appointment Update',
    newConsultation: 'New Consultation',
    connectionRestored: 'Connection restored',
    supportTeam: 'Support Team',
    // Auth
    accessDenied: 'Access denied. Please use the mobile application.',
    invalidLogin: 'Invalid email or password. Please try again.',
    portalTitle: 'MedBook Portal',
    secureAccess: 'Secure staff access',
    signInTitle: 'Sign in to your account',
    emailAddress: 'Email address',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'Password',
    signInBtn: 'Sign In',
    signingInBtn: 'Signing in...',
    areYouDoctor: 'Are you a doctor?',
    applyToJoin: 'Apply to join our platform',
    // Availability Editor
    toggleTip: 'Tip: Toggle the checkbox to enable/disable a day, then set your available time slots',
    fromTime: 'From',
    toTime: 'To',
    slotDuration: 'Slot Duration',
    minText: 'min',
    saveSchedule: 'Save Schedule',
    // Doctor Appointments & Patients
    apptConfirmed: 'Appointment confirmed',
    errConfirmAppt: 'Failed to confirm appointment',
    apptPending: 'Appointment moved to pending',
    errUnconfirmAppt: 'Failed to unconfirm appointment',
    apptCancelled: 'Appointment cancelled',
    errCancelAppt: 'Failed to cancel appointment',
    apptCompleted: 'Appointment marked as completed',
    errCompleteOp: 'Failed to complete operation',
    apptDeleted: 'Appointment deleted',
    errDeleteAppt: 'Failed to delete appointment',
    historyCleared: 'History cleared successfully',
    errClearHistory: 'Failed to clear history',
    noDate: 'No Date',
    manageAppts: 'Manage patient appointments',
    refresh: 'Refresh',
    active: 'Active',
    history: 'History',
    searchApptQuery: 'Search patient, date, status...',
    clearHistoryBtn: 'Clear History',
    yesClearHistory: 'Yes, clear history',
    clearHistoryDesc: 'Are you sure? This will permanently remove all past appointments from your records. This action cannot be undone.',
    cancel: 'Cancel',
    All: 'All',
    msgSent: 'Message sent',
    errMsgSent: 'Failed to send message',
    patientsAndAppts: 'Patients and Appointments',
    registeredPatients: 'Patients registered',
    registeredAppts: 'Appointments',
    day: 'Day',
    allPatients: 'All Patients',
    searchPatientName: 'Search patient name...',
    noApptsScheduled: 'No appointments scheduled',
    recordsLocked: 'Records Locked (No appointment today)',
    sendMessage: 'Send Message',
    patientName: 'Patient name',
    genderAndAge: 'Gender and age',
    lastVisit: 'Last visit',
    actions: 'Actions',
    noResultsFound: 'No results found',
    years: 'years',
    records: 'Records',
    locked: 'Locked',
    messageBtn: 'Message',
    patientDetails: 'Patient Details',
    age: 'Age',
    notSet: 'Not set',
    gender: 'Gender',
    totalAppts: 'Total Appointments',
    none: 'None',
    bloodType: 'Blood Type',
    allergies: 'Allergies',
    viewFullRecords: 'View Full Records',
    sendDirectMsg: 'Send a direct message to',
    writeMsg: 'Write your message...',
    sending: 'Sending...',
    send: 'Send',
    // Patient Records, Workspace, Summary
    aiAnalysisUpdated: 'AI Health Analysis Updated',
    errAiAnalysis: 'AI Analysis failed. Check if AI server is running.',
    recordAdded: 'Record added successfully',
    errAddRecord: 'Failed to add record',
    deleted: 'Deleted',
    errDelete: 'Failed to delete',
    accessRestricted: 'Access Restricted',
    accessRestrictedDesc: 'For privacy and security reasons, you can only access and modify a patient\'s medical profile on the actual day of their scheduled appointment.',
    returnToPatientsList: 'Return to Patients List',
    profile: 'Profile',
    visits: 'Visits',
    chronic: 'Chronic',
    medications: 'Medications',
    vitals: 'Vitals',
    surgeries: 'Surgeries',
    scansLabs: 'Scans / Labs',
    noRecordsFound: 'No records found.',
    noVisitsHistory: 'No visits history',
    noAllergies: 'No allergies',
    noChronic: 'No chronic diseases',
    noMedications: 'No medications',
    noVitals: 'No vitals',
    fullName: 'Full Name',
    email: 'Email',
    phone: 'Phone',
    weightL: 'Weight',
    height: 'Height',
    smoking: 'Smoking',
    emergencyContact: 'Emergency Contact',
    emergencyPhone: 'Emergency Phone',
    yes: 'Yes',
    no: 'No',
    daily: 'Daily',
    aiHealthInsights: 'AI Health Insights',
    automatedAnalysis: 'Automated analysis of patient history',
    analyzing: 'Analyzing...',
    refreshAnalysis: 'Refresh Analysis',
    generateAnalysis: 'Generate Analysis',
    aiAnalysisReport: 'AI Analysis Report',
    noHealthAnalysis: 'No health analysis has been generated for this patient yet.',
    clickToAnalyze: 'Click the button above to analyze the medical history.',
    unknownDoctor: 'Unknown Doctor',
    specialist: 'Specialist',
    complaintLabel: 'Complaint',
    noneRecorded: 'None recorded',
    aiSummary: 'AI Summary',
    readLess: 'Read Less',
    readMore: 'Read More',
    viewFullDetails: 'View Full Details',
    added: 'Added',
    allergenName: 'Allergen Name *',
    type: 'Type',
    severity: 'Severity',
    reaction: 'Reaction',
    diseaseName: 'Disease Name *',
    doctorNotes: 'Doctor Notes',
    medicationName: 'Medication Name *',
    genericName: 'Generic Name',
    form: 'Form',
    dosage: 'Dosage',
    frequency: 'Frequency',
    timesPerDay: 'Times/Day',
    doseTimes: 'Dose Times (comma separated)',
    daysOfWeek: 'Days of Week',
    startDate: 'Start Date',
    endDateOpt: 'End Date (Optional)',
    pillsRemaining: 'Pills Remaining',
    refillThreshold: 'Refill Threshold',
    chronicMedication: 'Chronic Medication',
    instructions: 'Instructions',
    readingType: 'Reading Type',
    valueReq: 'Value *',
    value2: 'Value 2',
    unit: 'Unit',
    notes: 'Notes',
    surgeryName: 'Surgery Name *',
    date: 'Date',
    hospital: 'Hospital',
    visitSummaryNotFound: 'Visit summary not found',
    back: 'Back',
    printReport: 'Print Report',
    downloadPdf: 'Download PDF',
    visitSummary: 'Visit Summary',
    finalMedicalReport: 'Final Medical Report & Prescription',
    visitDetails: 'Visit Details',
    idLabel: 'ID:',
    yearsOld: 'Years Old',
    bloodTypeLabel: 'Blood Type:',
    knownAllergies: 'Known Allergies',
    pastVisitsSummary: 'Past Visits Summary (Last 8 Months)',
    noVisitsRecorded: 'No visits recorded in the last 8 months.',
    chiefComplaintLabel: 'Chief Complaint',
    assessmentDiagnosis: 'Assessment / Diagnosis',
    treatmentPlan: 'Treatment Plan',
    followUpRequiredLabel: 'Follow-up Required',
    vitalSigns: 'Vital Signs',
    prescribedMedications: 'Prescribed Medications',
    medicationTh: 'Medication',
    dosageFreqTh: 'Dosage & Freq',
    durationTh: 'Duration',
    chronicTag: 'Chronic',
    electronicPatientMgmt: 'Electronic Patient Management System',
    summaryDisclaimer: 'This summary is auto-generated and does not substitute professional medical advice.',
    errEnterComplaint: 'Please enter the chief complaint first',
    aiSuggestionsGenerated: 'AI suggestions generated successfully',
    errAiAssist: 'Failed to get AI assistance',
    draftSaved: 'Draft saved successfully',
    errSaveDraft: 'Failed to save draft',
    visitClosed: 'Visit closed successfully',
    errCloseVisit: 'Failed to close visit',
    inProgress: 'In Progress',
    closed: 'Closed',
    visitWorkspace: 'Visit Workspace',
    saving: 'Saving...',
    saveDraft: 'Save Draft',
    finishAndClose: 'Finish & Close',
    criticalAlertHeader: 'CRITICAL ALERT',
    patientProfile: 'Patient Profile',
    aiHealthReport: 'AI Health Report',
    vitalDetails: 'Vital Details',
    unknown: 'Unknown',
    recorded: 'Recorded',
    lifeThreatening: 'Life-threatening:',
    chronicConditions: 'Chronic Conditions',
    activeMedications: 'Active Medications',
    recentVisitsLast8: 'Recent Visits (Last 8 Months)',
    subjective: 'Subjective',
    hpi: 'History of Present Illness',
    objectiveVitals: 'Objective & Vitals',
    sysBp: 'Sys BP',
    diaBp: 'Dia BP',
    heartRate: 'Heart Rate',
    temp: 'Temp',
    sugar: 'Sugar',
    spo2: 'SpO2',
    examinationFindings: 'Examination Findings',
    assessment: 'Assessment',
    aiAnalyze: 'AI Analyze',
    planPrescriptions: 'Plan & Prescriptions',
    medicationsRx: 'Medications Rx',
    addDrug: 'Add Drug',
    noMedsPrescribed: 'No medications prescribed yet.',
    scheduleFollowUp: 'Schedule Follow-up',
    time: 'Time',
    lockAndCloseVisit: 'Lock & Close Visit',
    finalizeRecordWarn: 'This will finalize the medical record. You won\'t be able to edit these notes afterwards.',
    goBack: 'Go Back',
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    errLoadAppts: 'Failed to load appointments',
    visitStarted: 'Visit started successfully',
    errStartVisit: 'Failed to start visit',
    todays: "Today's",
    searchPatient: 'Search patient...',
    todayWord: 'Today',
    noApptsTodayHeader: 'No Appointments Today',
    clearSchedule: 'You have a clear schedule for today.',
    starting: 'Starting...',
    startVisit: 'Start Visit',
    viewRecord: 'View Record',
    awaitingConfirm: 'Awaiting confirmation',
    aiReports: 'AI Reports',
    reportsFound: 'report(s) found',
    english: 'English',
    arabic: 'العربية',
    noReportsAvailable: 'No reports available',
    adjustFilters: 'Try adjusting your filters',
    Low: 'Low',
    Medium: 'Medium',
    High: 'High',
    errLoadConv: 'Failed to load conversation',
    uploading: 'Uploading',
    sent: 'sent',
    errUpload: 'Failed to upload',
    confirmDeleteConv: 'Are you sure you want to delete this conversation? This action cannot be undone.',
    convDeleted: 'Conversation deleted successfully',
    errDeleteConv: 'Failed to delete conversation',
    conversations: 'Conversations',
    connectRealtime: 'Connect with your patients in real-time',
    activeConvs: 'Active Conversations',
    sessionsWord: 'session(s)',
    noConvsYet: 'No conversations yet',
    selectConv: 'Select a conversation to start',
    highUrgency: 'High Urgency',
    deleteConv: 'Delete Conversation',
    attachment: 'Attachment',
    document: 'Document',
    you: 'You',
    typeMessage: 'Type your message...',
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    profileSaved: 'Profile saved successfully',
    errSaveProfile: 'Failed to save data',
    photoUploaded: 'Photo uploaded successfully',
    errUploadPhoto: 'Failed to upload photo',
    doctorProfile: 'Doctor Profile',
    manageProfileDesc: 'Manage your personal and professional profile information',
    doctorName: 'Doctor Name',
    generalPractice: 'General Practice',
    reviewsWord: 'reviews',
    availableNow: 'Available Now',
    notAvailable: 'Not Available',
    editProfile: 'Edit Profile',
    enterFullName: 'Enter your full name',
    consultFee: 'Consultation Fee ($)',
    doctorBio: 'Doctor Biography',
    bioPlaceholder: 'Write a brief description about your specialization, experience, and approach to patient care...',
    saveChanges: 'Save Changes',
    patientReviews: 'Patient Reviews',
    totalWord: 'total',
    noReviewsYet: 'No reviews yet. Complete appointments to receive reviews!',
    anonymous: 'Anonymous',
    errLoadReviews: 'Failed to load reviews',
    reviewsAndRatings: 'Reviews & Ratings',
    patientFeedbackDesc: 'Patient feedback about your practice',
    overallRating: 'Overall Rating',
    outOf5: 'out of 5',
    noReviewsDesc2: 'No reviews yet. Great care leads to great reviews!',
    errLoadStaff: 'Failed to load staff list',
    fillAllFields: 'Please fill all fields',
    secAdded: 'Secretary added successfully!',
    errAddSec: 'Failed to add secretary',
    confirmRemoveStaff: 'Are you sure you want to remove this staff member?',
    staffRemoved: 'Staff member removed',
    errRemoveStaff: 'Failed to remove staff member',
    staffMgmt: 'Staff Management',
    manageStaffDesc: 'Manage your clinic secretaries and staff',
    addNewSec: 'Add New Secretary',
    egName: 'e.g. Mona Ahmed',
    password: 'Password',
    addStaffBtn: 'Add Staff Member',
    currentStaff: 'Current Staff',
    loading: 'Loading...',
    noStaffYet: 'No staff members added yet',
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    scheduleSaved: 'Schedule saved successfully',
    errSaveSchedule: 'Failed to save schedule',
    manageWeeklyTimes: 'Manage your weekly reception times',
    weeklyAvailability: 'Weekly Availability',
    scheduleVisible: 'Schedule is now visible to patients',
    scheduleHidden: 'Schedule is now hidden from patients',
    visibleToPatients: 'Visible to Patients',
    hiddenFromPatients: 'Hidden from Patients',
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Dashboard
    todaysAppts: "Today's Appointments",
    totalPatients: 'Total Patients',
    weeklySessions: 'Weekly Sessions',
    doctorDashboard: 'Doctor Dashboard',
    welcomeDoctor: "Welcome back! Here's your practice overview",
    live: 'Live',
    viewAll: 'View All',
    noApptsToday: 'No appointments today',
    enjoyFreeTime: 'Enjoy your free time!',
    sessions: 'Sessions',
    recentAiReports: 'Recent AI Reports',
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Dashboard
    // Apply Page
    language: 'العربية',
    errInvalidFile: 'Only PDF, JPG, or PNG files are allowed.',
    errFileTooLarge: 'File must be less than 5 MB.',
    errNoSpecialty: 'Please select a specialty.',
    errNoLicenseDoc: 'Please upload your license/credential document.',
    errNoLicense: 'License / National ID is required.',
    errSubmitFailed: 'Failed to submit application. Please try again.',
    appReceived: 'Application Received!',
    appReceivedDesc1: 'Your application has been received. We will contact you soon at ',
    appReceivedDesc2: ' after reviewing your documents.',
    backToLogin: 'Back to Login',
    applyAsDoctor: 'Apply as a Doctor',
    joinNetwork: 'Join our network of healthcare professionals',
    phoneNumber: 'Phone Number',
    yearsExp: 'Years of Experience',
    specialty: 'Specialty',
    selectSpecialty: '-- Select Specialty --',
    licenseId: 'License / National ID',
    profBio: 'Professional Bio',
    msgToAdmin: 'Message to Admin (optional)',
    profilePhoto: 'Profile Photo (Professional Headshot)',
    uploadPhotoDesc: 'Upload a professional photo for your profile.',
    uploadPhotoRec: 'Recommended: Square image, max 2MB',
    docsLabel: 'Documents (PDF, JPG, PNG — max 5 MB)',
    uploadOrDrag: 'Click to upload or drag and drop',
    uploadDocsRec: 'PDF, JPG, PNG up to 5 MB',
    submitting: 'Submitting...',
    submitApp: 'Submit Application',
    // Statuses
    Pending: 'Pending',
    Confirmed: 'Confirmed',
    Cancelled: 'Cancelled',
    Completed: 'Completed',
    NoShow: 'No Show',
    Rescheduled: 'Rescheduled',
    // Admin
    adminDashboard: 'Admin Dashboard',
    adminPortal: 'Admin Portal',
    totalUsers: 'Total Users',
    activeDoctors: 'Active Doctors',
    todaysSessions: "Today's Sessions",
    sessionActivity: 'Session Activity',
    systemThroughput: 'System throughput over last 30 intervals',
    caseSeverity: 'Case Severity',
    demoData: 'Demo Data',
    latestIntelligence: 'Latest intelligence as of',
    urgencyLow: 'Low',
    urgencyMedium: 'Medium',
    urgencyHigh: 'High',
    urgencyEmergency: 'Emergency',
    doctorApplications: 'Doctor Applications',
    reviewManageApplicants: 'Review and manage applicants',
    viewDocument: 'View Document',
    downloadDocument: 'Download Document',
    rejectApplication: 'Reject Application',
    youAreAboutToReject: 'You are about to reject',
    messageToAdmin: 'Message to Admin',
    bio: 'Bio',
    aiModelManagement: 'AI Model Management',
    monitorManageModels: 'Monitor and manage deployed AI models',
    systemStatus: 'System Status',
    deployedModels: 'Deployed Models',
    inventoryAgentModels: 'Inventory of deployed agent models and versions',
    initializingEnv: 'Initializing Environment...',
    storage: 'Storage',
    security: 'Security',
    stable: 'STABLE',
    optimal: 'OPTIMAL',
    encrypted: 'ENCRYPTED',
    systemAnalytics: 'System Analytics & Statistics',
    aiPerformanceMetrics: 'AI-driven performance metrics and system behavioral analysis',
    dailySessions: 'Daily Sessions',
    operationalLoad: 'Operational load across the weekly spectrum',
    growthChart: 'Growth Chart',
    monthlyAcquisition: 'Monthly acquisition of new system entities',
    analysisMatrix: 'Analysis Matrix',
    newRegistries: 'New Registries',
    aiPredictive: 'AI Predictive',
    expectedGrowth: '+18% expected growth next month based on current trends.',
    realTimeStream: 'Real-time Stream Active',
    generateReport: 'Generate Report',
    manageComplaints: 'Manage user complaints and technical requests',
    viewComplaints: 'View complaints from users and doctors',
    supportConversations: 'Support Conversations',
    noSupportTickets: 'No support tickets',
    activeTicket: 'Active Ticket',
    selectSupportTicket: 'Select a support ticket to respond',
    userManagement: 'User Management',
    manageAllDoctors: 'Manage all doctors, patients and admin accounts in one place',
    totalRegisteredUsers: 'Total Registered Users',
    platformCapacity: 'Platform capacity: 75% utilized',
    addUser: 'Add User',
    filterByRole: 'Filter by Role',
    connectionLost: 'Connection Lost',
    tryReconnecting: 'Try Reconnecting',
    useDemoData: 'Use Demo Data',
    reject: 'Reject',
    loadingApplications: 'Loading applications...',
    // Secretary
    secretaryPortal: 'Secretary Portal',
    manageDoctorAppts: "Manage doctor's appointments",
    doctorSchedule: 'Doctor Schedule',
    manageDoctorReception: "Manage your doctor's weekly reception times",
    bookAppointment: 'Book Appointment',
    bookNewAppointment: 'Book New Appointment',
    rescheduleAppointment: 'Reschedule Appointment',
    reschedule: 'Reschedule',
    loadingAppts: 'Loading appointments...',
    noApptsFound: 'No appointments found',
    patientType: 'Patient Type',
    existingPatient: 'Existing Patient',
    newWalkIn: 'New Walk-in',
    searchPatientByName: 'Search patient by name...',
    noPatientsFound: 'No patients found',
    enterPatientName: 'Enter patient name',
    enterPatientEmail: 'Enter patient email',
    enterPatientPhone: 'Enter patient phone',
    loadingDoctor: 'Loading doctor...',
    paymentMethod: 'Payment Method',
    cashOnArrival: 'Cash on Arrival',
    visaOnline: 'Visa (Online)',
    optionalNotes: 'Optional notes...',
    newDate: 'New Date',
    newTime: 'New Time',
    reasonOptional: 'Reason (optional)',
    reasonPlaceholder: 'e.g. Patient request',
    errLoadDoctorInfo: 'Failed to load doctor info',
    errSearchPatients: 'Failed to search patients',
    apptRescheduled: 'Appointment rescheduled',
    errReschedule: 'Failed to reschedule',
    errSelectDateTime: 'Please select date and time',
    errFillRequired: 'Please fill all required fields',
    errSelectPatient: 'Please select a patient',
    errFillNamePhone: 'Please fill patient name and phone',
    apptBooked: 'Appointment booked successfully',
    errBookAppt: 'Failed to book appointment',
    markedNoShow: 'Marked as no-show',
    errMarkNoShow: 'Failed to mark no-show',
    errLoadSchedule: 'Failed to load doctor schedule',
    scheduleSavedSuccess: 'Doctor schedule saved successfully',
    errSaveScheduleGeneric: 'Failed to save schedule',
    errUpdateVisibility: 'Failed to update visibility',
    scheduleVisibleToPatients: 'Schedule is now visible to patients',
    scheduleHiddenFromPatients: 'Schedule is now hidden from patients',
    // Appointment table
    noAppts: 'No appointments',
    apptDetails: 'Appointment Details',
    dateTime: 'Date/Time',
    notSpecified: 'Not specified',
    cash: 'Cash',
    onArrival: 'On arrival',
    card: 'Card',
    confirmApptTitle: 'Confirm Appointment',
    confirmApptMsg: 'Are you sure you want to confirm this appointment?',
    unconfirmApptTitle: 'Move Back To Pending',
    unconfirmApptMsg: 'Do you want to move this appointment back to pending?',
    cancelApptTitle: 'Cancel Appointment',
    cancelApptMsg: 'Are you sure you want to cancel this appointment?',
    completeApptTitle: 'Complete Appointment',
    completeApptMsg: 'Are you sure you want to mark this appointment as completed?',
    deleteApptTitle: 'Delete Appointment',
    deleteApptMsg: 'Are you sure you want to delete/cancel this appointment?',
    noShowTitle: 'Mark No-Show',
    noShowMsg: 'Patient did not show up for this appointment. Mark as no-show?',
    rescheduleApptTitle: 'Reschedule Appointment',
    rescheduleApptMsg: 'This will open the reschedule flow.',
    unconfirm: 'Unconfirm',
    complete: 'Complete',
    noShow: 'No-Show',
    details: 'Details',
    confirm: 'Confirm',
    delete: 'Delete',
    statusLabel: 'Status',
    // Urgency
  
    // Additional
    doctorNotFound: 'Doctor not found',
    licensedCertified: 'Licensed & Certified',
    consultationFee: 'Consultation Fee',
    bioNotAvailable: 'Biography not available at this moment',
    contactInfo: 'Contact Information',
    experience: 'Experience',
    specificDays: 'Specific Days',
    everyOtherDay: 'Every Other Day',
    reportProcessing: 'Report data is currently being processed or unavailable.',
    view: 'View',
    ourDoctors: 'Our Doctors',
    findRightDoctor: 'Find the right doctor for you',
    allSpecialties: 'All Specialties',
    noDoctorsFound: 'No doctors found',
    noDoctorsMatched: 'No doctors matched your search criteria',
    clickForSummary: '(Click for summary)',
},
  ar: {
    search: 'بحث...',
    notifications: 'الإشعارات',
    noNotifications: 'لا توجد إشعارات',
    light: 'فاتح',
    dark: 'داكن',
    switchToLight: 'التبديل للوضع الفاتح',
    switchToDark: 'التبديل للوضع الداكن',
    logOut: 'تسجيل الخروج',
    loggedOut: 'تم تسجيل الخروج بنجاح',
    dashboard: 'لوحة التحكم',
    todaysVisits: 'زيارات اليوم',
    appointments: 'المواعيد',
    patients: 'المرضى',
    reviews: 'التقييمات',
    messages: 'الرسائل',
    manageStaff: 'إدارة الفريق',
    schedule: 'الجدول',
    myProfile: 'ملفي الشخصي',
    users: 'المستخدمون',
    statistics: 'الإحصائيات',
    applications: 'طلبات الانضمام',
    supportCenter: 'مركز الدعم',
    systemAdministrator: 'مدير النظام',
    secretary: 'السكرتير',
    doctor: 'الطبيب',
    smartMedical: 'طبي ذكي',
    newBooking: 'حجز جديد',
    cancelled: 'تم الإلغاء',
    appointmentUpdate: 'تحديث الموعد',
    newConsultation: 'استشارة جديدة',
    connectionRestored: 'تمت استعادة الاتصال',
    supportTeam: 'فريق الدعم',
    // Auth
    accessDenied: 'تم رفض الوصول. يرجى استخدام تطبيق الهاتف.',
    invalidLogin: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    portalTitle: 'بوابة MedBook',
    secureAccess: 'وصول آمن للموظفين',
    signInTitle: 'تسجيل الدخول لحسابك',
    emailAddress: 'البريد الإلكتروني',
    emailPlaceholder: 'you@example.com',
    passwordLabel: 'كلمة المرور',
    signInBtn: 'تسجيل الدخول',
    signingInBtn: 'جاري تسجيل الدخول...',
    areYouDoctor: 'هل أنت طبيب؟',
    applyToJoin: 'قدم طلب انضمام لمنصتنا',
    // Availability Editor
    toggleTip: 'نصيحة: قم بتفعيل مربع الاختيار لتنشيط اليوم، ثم حدد أوقات عملك المتاحة',
    fromTime: 'من',
    toTime: 'إلى',
    slotDuration: 'مدة الجلسة',
    minText: 'دقيقة',
    saveSchedule: 'حفظ الجدول',
    // Doctor Appointments & Patients
    apptConfirmed: 'تم تأكيد الموعد',
    errConfirmAppt: 'فشل في تأكيد الموعد',
    apptPending: 'تم نقل الموعد إلى قيد الانتظار',
    errUnconfirmAppt: 'فشل في إلغاء تأكيد الموعد',
    apptCancelled: 'تم إلغاء الموعد',
    errCancelAppt: 'فشل في إلغاء الموعد',
    apptCompleted: 'تم تحديد الموعد كمكتمل',
    errCompleteOp: 'فشل في إتمام العملية',
    apptDeleted: 'تم حذف الموعد',
    errDeleteAppt: 'فشل في حذف الموعد',
    historyCleared: 'تم مسح السجل بنجاح',
    errClearHistory: 'فشل في مسح السجل',
    noDate: 'بدون تاريخ',
    manageAppts: 'إدارة مواعيد المرضى',
    refresh: 'تحديث',
    active: 'نشط',
    history: 'السجل',
    searchApptQuery: 'بحث: مريض، تاريخ، حالة...',
    clearHistoryBtn: 'مسح السجل',
    yesClearHistory: 'نعم، امسح السجل',
    clearHistoryDesc: 'هل أنت متأكد؟ سيتم حذف جميع المواعيد السابقة نهائياً من سجلاتك. لا يمكن التراجع عن هذا الإجراء.',
    cancel: 'إلغاء',
    All: 'الكل',
    msgSent: 'تم إرسال الرسالة',
    errMsgSent: 'فشل في إرسال الرسالة',
    patientsAndAppts: 'المرضى والمواعيد',
    registeredPatients: 'المرضى المسجلين',
    registeredAppts: 'المواعيد',
    day: 'يوم',
    allPatients: 'كل المرضى',
    searchPatientName: 'بحث باسم المريض...',
    noApptsScheduled: 'لا توجد مواعيد مجدولة',
    recordsLocked: 'السجلات مقفلة (لا يوجد موعد اليوم)',
    sendMessage: 'إرسال رسالة',
    patientName: 'اسم المريض',
    genderAndAge: 'الجنس والعمر',
    lastVisit: 'آخر زيارة',
    actions: 'الإجراءات',
    noResultsFound: 'لا توجد نتائج',
    years: 'سنوات',
    records: 'السجلات',
    locked: 'مقفل',
    messageBtn: 'رسالة',
    patientDetails: 'تفاصيل المريض',
    age: 'العمر',
    notSet: 'غير محدد',
    gender: 'الجنس',
    totalAppts: 'إجمالي المواعيد',
    none: 'لا يوجد',
    bloodType: 'فصيلة الدم',
    allergies: 'الحساسية',
    viewFullRecords: 'عرض السجلات الكاملة',
    sendDirectMsg: 'أرسل رسالة مباشرة إلى',
    writeMsg: 'اكتب رسالتك...',
    sending: 'جاري الإرسال...',
    send: 'إرسال',
    // Patient Records, Workspace, Summary
    aiAnalysisUpdated: 'تم تحديث التحليل الصحي الذكي',
    errAiAnalysis: 'فشل التحليل الذكي. تأكد من تشغيل سيرفر الذكاء الاصطناعي.',
    recordAdded: 'تمت إضافة السجل بنجاح',
    errAddRecord: 'فشل في إضافة السجل',
    deleted: 'تم الحذف',
    errDelete: 'فشل في الحذف',
    accessRestricted: 'الوصول مقيّد',
    accessRestrictedDesc: 'لأسباب تتعلق بالخصوصية والأمان، يمكنك فقط الوصول إلى الملف الطبي للمريض وتعديله في يوم الموعد المحدد.',
    returnToPatientsList: 'العودة لقائمة المرضى',
    profile: 'الملف الشخصي',
    visits: 'الزيارات',
    chronic: 'مزمن',
    medications: 'الأدوية',
    vitals: 'القراءات الحيوية',
    surgeries: 'العمليات الجراحية',
    scansLabs: 'الفحوصات / التحاليل',
    noRecordsFound: 'لا توجد سجلات.',
    noVisitsHistory: 'لا يوجد سجل زيارات',
    noAllergies: 'لا توجد حساسية',
    noChronic: 'لا توجد أمراض مزمنة',
    noMedications: 'لا توجد أدوية',
    noVitals: 'لا توجد قراءات حيوية',
    fullName: 'الاسم الكامل',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',
    weightL: 'الوزن',
    height: 'الطول',
    smoking: 'التدخين',
    emergencyContact: 'جهة اتصال الطوارئ',
    emergencyPhone: 'هاتف الطوارئ',
    yes: 'نعم',
    no: 'لا',
    daily: 'يومي',
    aiHealthInsights: 'رؤى صحية ذكية',
    automatedAnalysis: 'تحليل آلي لسجل المريض',
    analyzing: 'جاري التحليل...',
    refreshAnalysis: 'تحديث التحليل',
    generateAnalysis: 'توليد التحليل',
    aiAnalysisReport: 'تقرير التحليل الذكي',
    noHealthAnalysis: 'لم يتم إنشاء تحليل صحي لهذا المريض بعد.',
    clickToAnalyze: 'اضغط على الزر أعلاه لتحليل السجل الطبي.',
    unknownDoctor: 'طبيب غير معروف',
    specialist: 'أخصائي',
    complaintLabel: 'الشكوى',
    noneRecorded: 'لم يتم تسجيل شيء',
    aiSummary: 'ملخص ذكي',
    readLess: 'اقرأ أقل',
    readMore: 'اقرأ المزيد',
    viewFullDetails: 'عرض التفاصيل الكاملة',
    added: 'تمت الإضافة',
    allergenName: 'اسم المادة المسببة للحساسية *',
    type: 'النوع',
    severity: 'الخطورة',
    reaction: 'التفاعل',
    diseaseName: 'اسم المرض *',
    doctorNotes: 'ملاحظات الطبيب',
    medicationName: 'اسم الدواء *',
    genericName: 'الاسم العلمي',
    form: 'النموذج',
    dosage: 'الجرعة',
    frequency: 'التكرار',
    timesPerDay: 'مرات/يوم',
    doseTimes: 'أوقات الجرعات (مفصولة بفاصلة)',
    daysOfWeek: 'أيام الأسبوع',
    startDate: 'تاريخ البدء',
    endDateOpt: 'تاريخ الانتهاء (اختياري)',
    pillsRemaining: 'الحبوب المتبقية',
    refillThreshold: 'حد إعادة التعبئة',
    chronicMedication: 'أدوية مزمنة',
    instructions: 'التعليمات',
    readingType: 'نوع القراءة',
    valueReq: 'القيمة *',
    value2: 'القيمة 2',
    unit: 'الوحدة',
    notes: 'ملاحظات',
    surgeryName: 'اسم العملية *',
    date: 'التاريخ',
    hospital: 'المستشفى',
    visitSummaryNotFound: 'ملخص الزيارة غير موجود',
    back: 'رجوع',
    printReport: 'طباعة التقرير',
    downloadPdf: 'تحميل PDF',
    visitSummary: 'ملخص الزيارة',
    finalMedicalReport: 'التقرير الطبي النهائي والوصفة',
    visitDetails: 'تفاصيل الزيارة',
    idLabel: 'الرقم:',
    yearsOld: 'سنة',
    bloodTypeLabel: 'فصيلة الدم:',
    knownAllergies: 'الحساسية المعروفة',
    pastVisitsSummary: 'ملخص الزيارات السابقة (آخر 8 أشهر)',
    noVisitsRecorded: 'لم يتم تسجيل زيارات في آخر 8 أشهر.',
    chiefComplaintLabel: 'الشكوى الرئيسية',
    assessmentDiagnosis: 'التقييم / التشخيص',
    treatmentPlan: 'خطة العلاج',
    followUpRequiredLabel: 'متابعة مطلوبة',
    vitalSigns: 'العلامات الحيوية',
    prescribedMedications: 'الأدوية الموصوفة',
    medicationTh: 'الدواء',
    dosageFreqTh: 'الجرعة والتكرار',
    durationTh: 'المدة',
    chronicTag: 'مزمن',
    electronicPatientMgmt: 'نظام إدارة المرضى الإلكتروني',
    summaryDisclaimer: 'هذا الملخص تم إنشاؤه آلياً ولا يُغني عن الاستشارة الطبية المتخصصة.',
    errEnterComplaint: 'يرجى إدخال الشكوى الرئيسية أولاً',
    aiSuggestionsGenerated: 'تم توليد الاقتراحات الذكية بنجاح',
    errAiAssist: 'فشل في الحصول على المساعدة الذكية',
    draftSaved: 'تم حفظ المسودة بنجاح',
    errSaveDraft: 'فشل في حفظ المسودة',
    visitClosed: 'تم إغلاق الزيارة بنجاح',
    errCloseVisit: 'فشل في إغلاق الزيارة',
    inProgress: 'قيد التنفيذ',
    closed: 'مغلق',
    visitWorkspace: 'مساحة عمل الزيارة',
    saving: 'جاري الحفظ...',
    saveDraft: 'حفظ المسودة',
    finishAndClose: 'إنهاء وإغلاق',
    criticalAlertHeader: 'تنبيه حرج',
    patientProfile: 'ملف المريض',
    aiHealthReport: 'التقرير الصحي الذكي',
    vitalDetails: 'تفاصيل القراءات الحيوية',
    unknown: 'غير معروف',
    recorded: 'مسجّل',
    lifeThreatening: 'مهدد للحياة:',
    chronicConditions: 'الأمراض المزمنة',
    activeMedications: 'الأدوية الحالية',
    recentVisitsLast8: 'الزيارات الأخيرة (آخر 8 أشهر)',
    subjective: 'الشكوى الذاتية',
    hpi: 'تاريخ المرض الحالي',
    objectiveVitals: 'الفحص الموضوعي والقراءات الحيوية',
    sysBp: 'ض. انقباضي',
    diaBp: 'ض. انبساطي',
    heartRate: 'معدل ضربات القلب',
    temp: 'الحرارة',
    sugar: 'السكر',
    spo2: 'تشبع الأكسجين',
    examinationFindings: 'نتائج الفحص',
    assessment: 'التقييم',
    aiAnalyze: 'تحليل ذكي',
    planPrescriptions: 'الخطة والوصفات',
    medicationsRx: 'الوصفات الطبية',
    addDrug: 'إضافة دواء',
    noMedsPrescribed: 'لم يتم وصف أدوية بعد.',
    scheduleFollowUp: 'جدولة متابعة',
    time: 'الوقت',
    lockAndCloseVisit: 'قفل وإغلاق الزيارة',
    finalizeRecordWarn: 'سيتم تأكيد السجل الطبي نهائياً. لن تتمكن من تعديل هذه الملاحظات بعد ذلك.',
    goBack: 'رجوع',
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    errLoadAppts: 'فشل في تحميل المواعيد',
    visitStarted: 'تم بدء الزيارة بنجاح',
    errStartVisit: 'فشل في بدء الزيارة',
    todays: 'اليوم',
    searchPatient: 'بحث عن مريض...',
    todayWord: 'اليوم',
    noApptsTodayHeader: 'لا توجد مواعيد اليوم',
    clearSchedule: 'جدولك فاضي النهاردة.',
    starting: 'جاري البدء...',
    startVisit: 'بدء الزيارة',
    viewRecord: 'عرض السجل',
    awaitingConfirm: 'في انتظار التأكيد',
    aiReports: 'تقارير الذكاء الاصطناعي',
    reportsFound: 'تقرير/تقارير',
    english: 'English',
    arabic: 'العربية',
    noReportsAvailable: 'لا توجد تقارير متاحة',
    adjustFilters: 'حاول تعديل الفلاتر',
    Low: 'منخفض',
    Medium: 'متوسط',
    High: 'عالي',
    errLoadConv: 'فشل في تحميل المحادثة',
    uploading: 'جاري الرفع',
    sent: 'تم الإرسال',
    errUpload: 'فشل في الرفع',
    confirmDeleteConv: 'هل أنت متأكد من حذف هذه المحادثة؟ لا يمكن التراجع عن هذا الإجراء.',
    convDeleted: 'تم حذف المحادثة بنجاح',
    errDeleteConv: 'فشل في حذف المحادثة',
    conversations: 'المحادثات',
    connectRealtime: 'تواصل مع مرضاك في الوقت الفعلي',
    activeConvs: 'المحادثات النشطة',
    sessionsWord: 'جلسة/جلسات',
    noConvsYet: 'لا توجد محادثات بعد',
    selectConv: 'اختر محادثة للبدء',
    highUrgency: 'عاجل جداً',
    deleteConv: 'حذف المحادثة',
    attachment: 'مرفق',
    document: 'مستند',
    you: 'أنت',
    typeMessage: 'اكتب رسالتك...',
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    profileSaved: 'تم حفظ الملف الشخصي بنجاح',
    errSaveProfile: 'فشل في حفظ البيانات',
    photoUploaded: 'تم رفع الصورة بنجاح',
    errUploadPhoto: 'فشل في رفع الصورة',
    doctorProfile: 'الملف الشخصي للطبيب',
    manageProfileDesc: 'إدارة معلوماتك الشخصية والمهنية',
    doctorName: 'اسم الطبيب',
    generalPractice: 'طب عام',
    reviewsWord: 'تقييمات',
    availableNow: 'متاح الآن',
    notAvailable: 'غير متاح',
    editProfile: 'تعديل الملف الشخصي',
    enterFullName: 'أدخل اسمك الكامل',
    consultFee: 'رسوم الاستشارة ($)',
    doctorBio: 'نبذة عن الطبيب',
    bioPlaceholder: 'اكتب نبذة مختصرة عن تخصصك وخبرتك ومنهجك في رعاية المرضى...',
    saveChanges: 'حفظ التغييرات',
    patientReviews: 'تقييمات المرضى',
    totalWord: 'الإجمالي',
    noReviewsYet: 'لا توجد تقييمات بعد. أكمل المواعيد لتلقي التقييمات!',
    anonymous: 'مجهول',
    errLoadReviews: 'فشل في تحميل التقييمات',
    reviewsAndRatings: 'التقييمات والمراجعات',
    patientFeedbackDesc: 'تقييمات المرضى عن عيادتك',
    overallRating: 'التقييم العام',
    outOf5: 'من 5',
    noReviewsDesc2: 'لا توجد تقييمات بعد. الرعاية الجيدة تجلب تقييمات رائعة!',
    errLoadStaff: 'فشل في تحميل قائمة الموظفين',
    fillAllFields: 'يرجى ملء جميع الحقول',
    secAdded: 'تمت إضافة السكرتيرة بنجاح!',
    errAddSec: 'فشل في إضافة السكرتيرة',
    confirmRemoveStaff: 'هل أنت متأكد من إزالة هذا الموظف؟',
    staffRemoved: 'تمت إزالة الموظف',
    errRemoveStaff: 'فشل في إزالة الموظف',
    staffMgmt: 'إدارة الموظفين',
    manageStaffDesc: 'إدارة سكرتيرات العيادة والموظفين',
    addNewSec: 'إضافة سكرتيرة جديدة',
    egName: 'مثال: منى أحمد',
    password: 'كلمة المرور',
    addStaffBtn: 'إضافة موظف',
    currentStaff: 'الموظفون الحاليون',
    loading: 'جاري التحميل...',
    noStaffYet: 'لم يتم إضافة موظفين بعد',
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    scheduleSaved: 'تم حفظ الجدول بنجاح',
    errSaveSchedule: 'فشل في حفظ الجدول',
    manageWeeklyTimes: 'إدارة أوقات استقبالك الأسبوعية',
    weeklyAvailability: 'الأوقات المتاحة أسبوعياً',
    scheduleVisible: 'الجدول أصبح مرئياً للمرضى',
    scheduleHidden: 'الجدول أصبح مخفياً عن المرضى',
    visibleToPatients: 'مرئي للمرضى',
    hiddenFromPatients: 'مخفي عن المرضى',
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Dashboard
    todaysAppts: 'مواعيد اليوم',
    totalPatients: 'إجمالي المرضى',
    weeklySessions: 'جلسات الأسبوع',
    doctorDashboard: 'لوحة تحكم الطبيب',
    welcomeDoctor: 'مرحباً بك! إليك نظرة عامة على عيادتك',
    live: 'مباشر',
    viewAll: 'عرض الكل',
    noApptsToday: 'لا توجد مواعيد اليوم',
    enjoyFreeTime: 'استمتع بوقت فراغك!',
    sessions: 'الجلسات',
    recentAiReports: 'أحدث التقارير الذكية',
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Appointments & Patients
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Patient Records, Workspace, Summary
    // Patient Records, Workspace, Summary
    // Today, Reports, Chat
    // Profile & Reviews & Secretaries
    // Doctor Schedule
    // Doctor Dashboard
    // Apply Page
    language: 'English',
    errInvalidFile: 'يُسمح فقط بملفات PDF أو JPG أو PNG.',
    errFileTooLarge: 'يجب أن يكون حجم الملف أقل من 5 ميغابايت.',
    errNoSpecialty: 'يرجى اختيار التخصص.',
    errNoLicenseDoc: 'يرجى رفع رخصة مزاولة المهنة أو المستندات.',
    errNoLicense: 'رقم الرخصة / الهوية الوطنية مطلوب.',
    errSubmitFailed: 'فشل إرسال الطلب. يرجى المحاولة مرة أخرى.',
    appReceived: 'تم استلام طلبك!',
    appReceivedDesc1: 'تم استلام طلبك. سنتواصل معك قريباً على ',
    appReceivedDesc2: ' بعد مراجعة مستنداتك.',
    backToLogin: 'العودة لتسجيل الدخول',
    applyAsDoctor: 'انضم كطبيب',
    joinNetwork: 'انضم لشبكتنا من المتخصصين في الرعاية الصحية',
    phoneNumber: 'رقم الهاتف',
    yearsExp: 'سنوات الخبرة',
    specialty: 'التخصص',
    selectSpecialty: '-- اختر التخصص --',
    licenseId: 'رقم الرخصة / الهوية الوطنية',
    profBio: 'نبذة مهنية',
    msgToAdmin: 'رسالة للإدارة (اختياري)',
    profilePhoto: 'الصورة الشخصية (صورة احترافية)',
    uploadPhotoDesc: 'ارفع صورة احترافية لملفك الشخصي.',
    uploadPhotoRec: 'موصى به: صورة مربعة، الحد الأقصى 2 ميغابايت',
    docsLabel: 'المستندات (PDF, JPG, PNG — الحد الأقصى 5 ميغابايت)',
    uploadOrDrag: 'اضغط للرفع أو اسحب وأفلت',
    uploadDocsRec: 'ملفات PDF, JPG, PNG حتى 5 ميغابايت',
    submitting: 'جاري الإرسال...',
    submitApp: 'إرسال الطلب',
    // Statuses
    Pending: 'قيد الانتظار',
    Confirmed: 'مؤكد',
    Cancelled: 'ملغي',
    Completed: 'مكتمل',
    NoShow: 'لم يحضر',
    Rescheduled: 'تم التأجيل',
    // Admin
    adminDashboard: 'لوحة تحكم الإدارة',
    adminPortal: 'بوابة الإدارة',
    totalUsers: 'إجمالي المستخدمين',
    activeDoctors: 'الأطباء النشطين',
    todaysSessions: 'جلسات اليوم',
    sessionActivity: 'نشاط الجلسات',
    systemThroughput: 'إنتاجية النظام خلال آخر 30 فترة',
    caseSeverity: 'خطورة الحالات',
    demoData: 'بيانات تجريبية',
    latestIntelligence: 'أحدث البيانات حتى',
    urgencyLow: 'منخفضة',
    urgencyMedium: 'متوسطة',
    urgencyHigh: 'عالية',
    urgencyEmergency: 'طوارئ',
    doctorApplications: 'طلبات الأطباء',
    reviewManageApplicants: 'مراجعة وإدارة المتقدمين',
    viewDocument: 'عرض المستند',
    downloadDocument: 'تحميل المستند',
    rejectApplication: 'رفض الطلب',
    youAreAboutToReject: 'أنت على وشك رفض',
    messageToAdmin: 'رسالة للمدير',
    bio: 'النبذة التعريفية',
    aiModelManagement: 'إدارة نماذج الذكاء الاصطناعي',
    monitorManageModels: 'مراقبة وإدارة النماذج المنشورة',
    systemStatus: 'حالة النظام',
    deployedModels: 'النماذج المنشورة',
    inventoryAgentModels: 'جرد لنماذج الإصدارات المنشورة',
    initializingEnv: 'جاري تهيئة البيئة...',
    storage: 'التخزين',
    security: 'الأمان',
    stable: 'مستقر',
    optimal: 'مثالي',
    encrypted: 'مشفر',
    systemAnalytics: 'تحليلات وإحصائيات النظام',
    aiPerformanceMetrics: 'مقاييس الأداء المدعومة بالذكاء الاصطناعي',
    dailySessions: 'الجلسات اليومية',
    operationalLoad: 'العبء التشغيلي خلال الأسبوع',
    growthChart: 'رسم بياني للنمو',
    monthlyAcquisition: 'الاستحواذ الشهري للمستخدمين',
    analysisMatrix: 'مصفوفة التحليل',
    newRegistries: 'تسجيلات جديدة',
    aiPredictive: 'الذكاء الاصطناعي التنبؤي',
    expectedGrowth: 'نمو متوقع بنسبة 18% الشهر القادم.',
    realTimeStream: 'البث المباشر نشط',
    generateReport: 'إنشاء تقرير',
    manageComplaints: 'إدارة شكاوى المستخدمين والطلبات التقنية',
    viewComplaints: 'عرض الشكاوى من المستخدمين والأطباء',
    supportConversations: 'محادثات الدعم',
    noSupportTickets: 'لا توجد تذاكر دعم',
    activeTicket: 'التذكرة النشطة',
    selectSupportTicket: 'اختر تذكرة للرد عليها',
    userManagement: 'إدارة المستخدمين',
    manageAllDoctors: 'إدارة جميع الأطباء والمرضى والمديرين',
    totalRegisteredUsers: 'إجمالي المستخدمين المسجلين',
    platformCapacity: 'سعة المنصة: 75% مستخدمة',
    addUser: 'إضافة مستخدم',
    filterByRole: 'تصفية حسب الدور',
    connectionLost: 'انقطع الاتصال',
    tryReconnecting: 'محاولة إعادة الاتصال',
    useDemoData: 'استخدام بيانات تجريبية',
    reject: 'رفض',
    loadingApplications: 'جاري تحميل الطلبات...',
    // Secretary
    secretaryPortal: 'بوابة السكرتير',
    manageDoctorAppts: 'إدارة مواعيد الطبيب',
    doctorSchedule: 'جدول الطبيب',
    manageDoctorReception: 'إدارة أوقات استقبال الطبيب الأسبوعية',
    bookAppointment: 'حجز موعد',
    bookNewAppointment: 'حجز موعد جديد',
    rescheduleAppointment: 'إعادة جدولة الموعد',
    reschedule: 'إعادة الجدولة',
    loadingAppts: 'جاري تحميل المواعيد...',
    noApptsFound: 'لم يتم العثور على مواعيد',
    patientType: 'نوع المريض',
    existingPatient: 'مريض مسجل',
    newWalkIn: 'مريض جديد',
    searchPatientByName: 'ابحث عن المريض بالاسم...',
    noPatientsFound: 'لم يتم العثور على مرضى',
    enterPatientName: 'أدخل اسم المريض',
    enterPatientEmail: 'أدخل بريد المريض',
    enterPatientPhone: 'أدخل هاتف المريض',
    loadingDoctor: 'جاري تحميل الطبيب...',
    paymentMethod: 'طريقة الدفع',
    cashOnArrival: 'نقداً عند الوصول',
    visaOnline: 'فيزا (أونلاين)',
    optionalNotes: 'ملاحظات اختيارية...',
    newDate: 'التاريخ الجديد',
    newTime: 'الوقت الجديد',
    reasonOptional: 'السبب (اختياري)',
    reasonPlaceholder: 'مثال: طلب المريض',
    errLoadDoctorInfo: 'فشل تحميل معلومات الطبيب',
    errSearchPatients: 'فشل البحث عن المرضى',
    apptRescheduled: 'تم إعادة جدولة الموعد',
    errReschedule: 'فشل إعادة الجدولة',
    errSelectDateTime: 'يرجى اختيار التاريخ والوقت',
    errFillRequired: 'يرجى ملء جميع الحقول المطلوبة',
    errSelectPatient: 'يرجى اختيار مريض',
    errFillNamePhone: 'يرجى إدخال اسم المريض ورقم الهاتف',
    apptBooked: 'تم حجز الموعد بنجاح',
    errBookAppt: 'فشل حجز الموعد',
    markedNoShow: 'تم التحديد كعدم حضور',
    errMarkNoShow: 'فشل تحديد عدم الحضور',
    errLoadSchedule: 'فشل تحميل جدول الطبيب',
    scheduleSavedSuccess: 'تم حفظ جدول الطبيب بنجاح',
    errSaveScheduleGeneric: 'فشل حفظ الجدول',
    errUpdateVisibility: 'فشل تحديث الظهور',
    scheduleVisibleToPatients: 'الجدول مرئي للمرضى الآن',
    scheduleHiddenFromPatients: 'الجدول مخفي عن المرضى الآن',
    // Appointment table
    noAppts: 'لا توجد مواعيد',
    apptDetails: 'تفاصيل الموعد',
    dateTime: 'التاريخ/الوقت',
    notSpecified: 'غير محدد',
    cash: 'نقداً',
    onArrival: 'عند الوصول',
    card: 'بطاقة',
    confirmApptTitle: 'تأكيد الموعد',
    confirmApptMsg: 'هل أنت متأكد أنك تريد تأكيد هذا الموعد؟',
    unconfirmApptTitle: 'إرجاع إلى قيد الانتظار',
    unconfirmApptMsg: 'هل تريد إرجاع هذا الموعد إلى قيد الانتظار؟',
    cancelApptTitle: 'إلغاء الموعد',
    cancelApptMsg: 'هل أنت متأكد أنك تريد إلغاء هذا الموعد؟',
    completeApptTitle: 'إتمام الموعد',
    completeApptMsg: 'هل أنت متأكد أنك تريد تحديد هذا الموعد كمكتمل؟',
    deleteApptTitle: 'حذف الموعد',
    deleteApptMsg: 'هل أنت متأكد أنك تريد حذف/إلغاء هذا الموعد؟',
    noShowTitle: 'تحديد عدم حضور',
    noShowMsg: 'المريض لم يحضر لهذا الموعد. هل تريد تحديده كعدم حضور؟',
    rescheduleApptTitle: 'إعادة جدولة الموعد',
    rescheduleApptMsg: 'سيتم فتح عملية إعادة الجدولة.',
    unconfirm: 'إلغاء التأكيد',
    complete: 'إتمام',
    noShow: 'عدم حضور',
    details: 'التفاصيل',
    confirm: 'تأكيد',
    delete: 'حذف',
    statusLabel: 'الحالة',
    // Urgency
    // Additional
    doctorNotFound: 'الطبيب غير موجود',
    licensedCertified: 'مرخص ومعتمد',
    consultationFee: 'رسوم الاستشارة',
    bioNotAvailable: 'النبذة التعريفية غير متاحة حالياً',
    contactInfo: 'معلومات الاتصال',
    experience: 'الخبرة',
    specificDays: 'أيام محددة',
    everyOtherDay: 'يوم بعد يوم',
    reportProcessing: 'بيانات التقرير قيد المعالجة أو غير متاحة حالياً.',
    view: 'عرض',
    ourDoctors: 'أطباؤنا',
    findRightDoctor: 'ابحث عن الطبيب المناسب لك',
    allSpecialties: 'كل التخصصات',
    noDoctorsFound: 'لا يوجد أطباء',
    noDoctorsMatched: 'لا يوجد أطباء مطابقين لبحثك',
    clickForSummary: '(اضغط للملخص)',

  },
} as const

type TranslationKey = keyof typeof dictionary.en

type LanguageContextValue = {
  lang: Lang
  isRTL: boolean
  setLanguage: (nextLang: Lang) => void
  toggleLanguage: () => void
  t: (key: TranslationKey) => string
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

function getInitialLanguage(): Lang {
  const stored = localStorage.getItem(LANGUAGE_KEY)
  if (stored === 'ar' || stored === 'en') return stored
  return navigator.language?.toLowerCase().startsWith('ar') ? 'ar' : 'en'
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>(getInitialLanguage)
  const isRTL = lang === 'ar'

  useEffect(() => {
    localStorage.setItem(LANGUAGE_KEY, lang)
    document.documentElement.lang = lang
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr'
    document.body.dir = isRTL ? 'rtl' : 'ltr'
  }, [lang, isRTL])

  const setLanguage = useCallback((nextLang: Lang) => setLang(nextLang), [])
  const toggleLanguage = useCallback(() => setLang(current => current === 'ar' ? 'en' : 'ar'), [])
  const t = useCallback((key: TranslationKey) => dictionary[lang][key] ?? dictionary.en[key], [lang])

  const value = useMemo(() => ({ lang, isRTL, setLanguage, toggleLanguage, t }), [lang, isRTL, setLanguage, toggleLanguage, t])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
